<a href="https://colab.research.google.com/github/bhagyashri27-ui/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard-/blob/main/sql_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Employee Database Management with SQLite and Pandas

Prompt: Write a Python program using SQLite and Pandas to create an employee database, insert sample employee records, perform SQL queries (filtering, grouping, aggregation, sorting), display the results, delete a specific employee record, add some new employee , also update salary and save the changes.

In [18]:
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create the employees table
cursor.execute('''
    CREATE TABLE employees (
        id INTEGER PRIMARY KEY,
        name TEXT,
        department TEXT,
        salary REAL
    )
''')
conn.commit()
print("Employee table created successfully.")

Employee table created successfully.

##### 1. Inserting Sample Employee Records

In [19]:
employees_data = [
    (1, 'Alia bhatt', 'Sales', 60000.00),
    (2, 'Sita raman', 'Marketing', 65000.00),
    (3, 'Chandu sarafh', 'Sales', 70000.00),
    (4, 'Diya singh', 'HR', 55000.00),
    (5, 'Mona diwakar', 'Marketing', 72000.00),
    (6, 'nick john', 'Engineering', 80000.00),
    (7, 'steeve pardesi', 'Engineering', 85000.00)
]

# Clear existing records before inserting to allow safe re-execution of this cell
cursor.execute("DELETE FROM employees")
conn.commit()

cursor.executemany('INSERT INTO employees VALUES (?, ?, ?, ?)', employees_data)
conn.commit()
print("Sample employee records inserted.")

# Display all records to verify insertion
df = pd.read_sql_query("SELECT * FROM employees", conn)
print("\nCurrent Employee Records:")
display(df)

Sample employee records inserted.

Current Employee Records:

   id            name   department   salary
0   1      Alia bhatt        Sales  60000.0
1   2      Sita raman    Marketing  65000.0
2   3   Chandu sarafh        Sales  70000.0
3   4      Diya singh           HR  55000.0
4   5    Mona diwakar    Marketing  72000.0
5   6       nick john  Engineering  80000.0
6   7  steeve pardesi  Engineering  85000.0

##### 2. Performing SQL Queries (Filtering, Grouping, Aggregation, Sorting)

In [20]:
# 1. Filtering: Employees in the 'Sales' department
print("\n--- Employees in the 'Sales' Department ---")
sales_employees_df = pd.read_sql_query("SELECT * FROM employees WHERE department = 'Sales'", conn)
display(sales_employees_df)

# 2. Grouping and Aggregation: Average salary by department
print("\n--- Average Salary by Department ---")
avg_salary_df = pd.read_sql_query("SELECT department, AVG(salary) AS average_salary FROM employees GROUP BY department", conn)
display(avg_salary_df)

# 3. Sorting: Employees sorted by salary in descending order
print("\n--- Employees Sorted by Salary (Descending) ---")
sorted_employees_df = pd.read_sql_query("SELECT * FROM employees ORDER BY salary DESC", conn)
display(sorted_employees_df)

--- Employees in the 'Sales' Department ---

   id           name department   salary
0   1     Alia bhatt      Sales  60000.0
1   3  Chandu sarafh      Sales  70000.0

--- Average Salary by Department ---

    department  average_salary
0  Engineering         82500.0
1           HR         55000.0
2    Marketing         68500.0
3        Sales         65000.0

--- Employees Sorted by Salary (Descending) ---

   id            name   department   salary
0   7  steeve pardesi  Engineering  85000.0
1   6       nick john  Engineering  80000.0
2   5    Mona diwakar    Marketing  72000.0
3   3   Chandu sarafh        Sales  70000.0
4   2      Sita raman    Marketing  65000.0
5   1      Alia bhatt        Sales  60000.0
6   4      Diya singh           HR  55000.0

##### 3. Deleting a Specific Employee Record

In [21]:
employee_id_to_delete = 4
cursor.execute("DELETE FROM employees WHERE id = ?", (employee_id_to_delete,))
conn.commit()
print(f"\nEmployee with ID {employee_id_to_delete} deleted.")

# Display all records to verify deletion
df_after_delete = pd.read_sql_query("SELECT * FROM employees", conn)
print("\nEmployee Records After Deletion:")
display(df_after_delete)

Employee with ID 4 deleted.

Employee Records After Deletion:

   id            name   department   salary
0   1      Alia bhatt        Sales  60000.0
1   2      Sita raman    Marketing  65000.0
2   3   Chandu sarafh        Sales  70000.0
3   5    Mona diwakar    Marketing  72000.0
4   6       nick john  Engineering  80000.0
5   7  steeve pardesi  Engineering  85000.0

##### 4. Adding New Employee Records

In [22]:
new_employees_data = [
    (8, 'Hina wagh', 'HR', 58000.00),
    (9, 'Ritvik singhaniya', 'Sales', 62000.00)
]

cursor.executemany('INSERT INTO employees (id, name, department, salary) VALUES (?, ?, ?, ?)', new_employees_data)
conn.commit()
print("\nNew employee records added.")

# Display all records to verify addition
df_after_add = pd.read_sql_query("SELECT * FROM employees", conn)
print("\nEmployee Records After Adding New Employees:")
display(df_after_add)

New employee records added.

Employee Records After Adding New Employees:

   id               name   department   salary
0   1         Alia bhatt        Sales  60000.0
1   2         Sita raman    Marketing  65000.0
2   3      Chandu sarafh        Sales  70000.0
3   5       Mona diwakar    Marketing  72000.0
4   6          nick john  Engineering  80000.0
5   7     steeve pardesi  Engineering  85000.0
6   8          Hina wagh           HR  58000.0
7   9  Ritvik singhaniya        Sales  62000.0

##### 5. Updating an Employee's Salary

In [23]:
employee_id_to_update = 1
new_salary = 63000.00
cursor.execute("UPDATE employees SET salary = ? WHERE id = ?", (new_salary, employee_id_to_update))
conn.commit()
print(f"\nSalary updated for employee with ID {employee_id_to_update} to {new_salary}.")

# Display all records to verify update
df_after_update = pd.read_sql_query("SELECT * FROM employees", conn)
print("\nEmployee Records After Salary Update:")
display(df_after_update)

# Close the connection (commented out to keep connection open for further operations)
# conn.close()
# print("\nDatabase connection closed.")

Salary updated for employee with ID 1 to 63000.0.

Employee Records After Salary Update:

   id               name   department   salary
0   1         Alia bhatt        Sales  63000.0
1   2         Sita raman    Marketing  65000.0
2   3      Chandu sarafh        Sales  70000.0
3   5       Mona diwakar    Marketing  72000.0
4   6          nick john  Engineering  80000.0
5   7     steeve pardesi  Engineering  85000.0
6   8          Hina wagh           HR  58000.0
7   9  Ritvik singhaniya        Sales  62000.0